# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
    -   id: black
        args: [--safe, --line-length=100, --preview]
        language_version: python3
    -   id: black
        types_or: [file]
        files: ^bin/
        args: [--safe, --line-length=100, --preview]
        language_version: python3

-   repo: https://github.com/pycqa/docformatter
    rev: v1.7.5
    hooks:
    -   id: docformatter
        additional_dependencies: [tomli]
        args: [--config, pyproject.toml]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
    -   id: mypy
        additional_dependencies: [
            types-PyYAML, types-tqdm, types-pytz,
            types-requests, types-setuptools,
        ]

-   repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
    -   id: flake8

ci:
    autoupdate_schedule: weekly
